apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-app-deployment
spec:
  replicas: 3  # Number of desired replicas
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      containers:
      - name: myapp
        image: huimeimbap/myapp:1.0
        ports:
        - containerPort: 5050 # Port your application listens on
